Separate User Info from ID token claims
curityio/oauth-agent-kotlin-spring-fapi pull request #16
Opened 2022-04-01 14:46 UTC by gary-archer

User Info now calls the user info endpoint.
A new /claims endpoint is for getting ID token protocol claims - customers can use either.
I have also consolidated error handling and logging so that it works the same as the Node OAuth Agent:
- nothing logged if there are no errors
- 4xx errors are single line without stack traces
- 5xx errors include stack traces

2022-04-07 14:54 UTC, mtrojanowski requested changes

2022-04-07 14:54 UTC, mtrojanowski commented on src/main/kotlin/io/curity/oauthagent/controller/ExceptionController.kt
> +        if (exception.statusCode >= 500) {
I would wrap the whole method in the condition. Something like this:

```java
if (exception.statusCode >= 500) {
   if(logger.isErrorEnabled) {
      val fields = getFieldsFromException(exception)
      logger.error(fields.joinToString)
   }
} else {
  if (logger.isInfoEnabled)) {
    val fields = getFieldsFromException(exception)
    logger.info(fields.joinToString)
  }
}
```

(The `getFieldsFromException(exception)` could actually be implemented as a method on `OAuthAgentException`)

I would do it this way because there is some work done to prepare the fields array and then join it into a string, but eventually, the logger might decide that it will not log this message at all, because of the settings used. The conditionals should be separate because `if (logger.isErrorEnabled)` is a condition that doesn't change through the lifetime of JVM and thus can be cached at many levels (either JIT compiler or CPU).

2022-04-07 14:54 UTC, mtrojanowski commented on src/main/kotlin/io/curity/oauthagent/controller/ExceptionController.kt
> +            val writer = StringWriter()
We could use `exception.stackTraceToString()`, though I think that it would be even better to pass the error to the logger:

```java
logger.error(fields.joinToString(), exception)
```

This will print the stack trace in addition to the log message.

2022-04-07 14:54 UTC, mtrojanowski commented on src/main/kotlin/io/curity/oauthagent/controller/ExceptionController.kt
> +        if (exception.message != null) {
I think this will be a bit more Kotlin-way:

```kotlin
exception.message?.apply {
   fields.add(this)
}
```

2022-04-07 14:54 UTC, mtrojanowski commented on src/main/kotlin/io/curity/oauthagent/exception/CookieDecryptionException.kt
> +    "Access denied due to invalid request details: ${cause?.message}",
I'm not sure if the message from the cause should be returned to the client. This can lead to some unexpected disclosure of information. E.g. the user in the browser will be able to see what libraries the OAuth Agent is using, based on the concrete message from an Exception. I think these messages should be rather logged, not exposed to the client. Alternatively, we could have a setting like in CIS "expose detailed messages", and append this message only when the setting is on, to facilitate development.

2022-04-07 14:54 UTC, mtrojanowski commented on src/main/kotlin/io/curity/oauthagent/exception/InvalidCookieException.kt
> +    "Access denied due to invalid request details: ${cause?.message}",
Same comment as in the CookieDecryptionException

2022-04-07 14:54 UTC, mtrojanowski commented on test/test-oauth-agent.sh
> +echo '15. Testing POST to /refresh from an untrusted origin ...'
I think next time we add some tests here we should change that to a counter ;)

2022-04-07 14:54 UTC, mtrojanowski commented on test/test-oauth-agent.sh
> +if [ "$HTTP_STATUS" != '500' ]; then
I don't think that posting a malformed JSON should result in a 500. It should be a 400 as this is something the client should correct, not the server.

2022-04-13 10:20 UTC, gary-archer commented on src/main/kotlin/io/curity/oauthagent/controller/ExceptionController.kt
> +        val formatter = SimpleDateFormat("MMM dd yyyy HH:mm:ss", Locale.getDefault())
Got rid of that - the time is already logged by log4j

2022-04-13 10:21 UTC, gary-archer commented on src/main/kotlin/io/curity/oauthagent/exception/CookieDecryptionException.kt
> +    "Access denied due to invalid request details: ${cause?.message}",
Hmm - I guess I thought that was a log message - well spotted - fixed

2022-04-13 10:21 UTC, gary-archer commented on test/test-oauth-agent.sh
> +if [ "$HTTP_STATUS" != '500' ]; then
Fixed in the UnhandledException class, by looking for an existing exception with a status

2022-04-13 11:19 UTC, mtrojanowski commented on src/main/kotlin/io/curity/oauthagent/controller/ExceptionController.kt
> +        val formatter = SimpleDateFormat("MMM dd yyyy HH:mm:ss", Locale.getDefault())
The `formatter` variable can also be removed now.

2022-04-13 11:20 UTC, mtrojanowski commented on src/main/kotlin/io/curity/oauthagent/controller/ExceptionController.kt
> +            val writer = StringWriter()
Should we change that to `exception.stackTraceToString()`? It does pretty much the same thing as here, but the code will read more nicely.

2022-04-13 11:21 UTC, mtrojanowski commented on src/main/kotlin/io/curity/oauthagent/controller/ExceptionController.kt
> +        if (exception.statusCode >= 500) {
I think changing this one can have a positive impact on performance. Can we reconsider implementing this?

2022-04-13 14:20 UTC, gary-archer commented on src/main/kotlin/io/curity/oauthagent/UserInfo.kt
> +            return objectMapper.readValue(Base64.getDecoder().decode(tokenParts[1]), UserInfoType())
done

2022-04-13 14:21 UTC, gary-archer commented on src/main/kotlin/io/curity/oauthagent/controller/ExceptionController.kt
> +        val formatter = SimpleDateFormat("MMM dd yyyy HH:mm:ss", Locale.getDefault())
good spot - done

2022-04-13 15:18 UTC, gary-archer commented on src/main/kotlin/io/curity/oauthagent/controller/ExceptionController.kt
> +            val writer = StringWriter()
Sorry - I missed this - and I agree that it is important - see latest code

2022-04-13 15:18 UTC, gary-archer commented on src/main/kotlin/io/curity/oauthagent/controller/ExceptionController.kt
> +        if (exception.statusCode >= 500) {
Agree - see latest code

2022-04-13 15:18 UTC, gary-archer commented on src/main/kotlin/io/curity/oauthagent/exception/InvalidCookieException.kt
> +    "Access denied due to invalid request details: ${cause?.message}",
done

2022-04-14 08:24 UTC, mtrojanowski approved these changes

2022-04-14 08:30 UTC, merged